---
name: CI/CD Pipeline

on:
  push:
    branches:
      - dev/v4/*
    tags:
      - v4.** # Triggers on any tag like v4.0.0, v4.1.2-rc.1, etc.

  pull_request:
    types: # The pull request events to listen for
      - opened
      - reopened
      - synchronize
    branches:
      - dev/v4 # The base branch that the pull request is targeting

  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
    with:
      ref: ${{ github.ref }}

  gotest:
    name: Go Tests
    if: ${{ vars.act != 'true' }}
    uses: ./.github/workflows/gotest.yaml
    with:
      ref: ${{ github.ref }}

  pytest:
    name: Python Tests
    if: ${{ vars.act != 'true' }}
    uses: ./.github/workflows/pytest.yaml
    with:
      ref: ${{ github.ref }}

  build-charts:
    name: Build Charts
    uses: ./.github/workflows/build-charts.yaml
    with:
      ref: ${{ github.ref }}

  build-images:
    name: Build Images
    uses: ./.github/workflows/build-images.yaml
    with:
      ref: ${{ github.ref }}
      artifact-bundle-prefix: images-${{ github.sha }}

  test-images:
    name: Test Images
    needs:
      - build-images
    uses: ./.github/workflows/test-images.yaml
    with:
      ref: ${{ github.ref }}
      artifact-bundle-prefix: images-${{ github.sha }}

  release:
    name: Release
    if: ${{ vars.act == 'true' || (startsWith(github.ref, 'refs/tags/v4.') && !contains(github.ref_name, '-')) }}
    needs:
      - lint
      - gotest
      - pytest
      - build-charts
      - build-images
      - test-images
    secrets: inherit
    uses: ./.github/workflows/release.yaml
    with:
      ref: ${{ github.ref }}
