---
name: Lint (Reusable)

on:
  workflow_call:
    inputs:
      ref:
        description: Git ref to checkout
        required: false
        type: string
        default: ${{ github.ref }}

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
      - name: Install Deps
        uses: ./.github/actions/setup-deps
      - name: Lint Dependencies
        shell: bash
        run: |
          make lint-deps
      - name: Lint Source Files
        shell: bash
        run: |
          make lint
