---
name: Release (Reusable)

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ${{ github.ref }}
        description: Git ref to checkout
      debug:
        type: boolean
        required: false
        default: false
        description: |
          Enable upterm debugging

          NOTE: only available when running locally with netkos/act
      components:
        type: string
        required: true
        description: >-
          The list of components to build images for, formatted as a space-separated list of strings.
      chart-registry:
        type: string
        required: false
        default: ghcr.io/emissary-ingress
        description: |
          OCI repository to push charts to

          Defaults to: ghcr.io/emissary-ingress
      image-registry:
        type: string
        required: false
        default: ghcr.io/emissary-ingress
        description: |
          OCI repository to push images to

          Defaults to: ghcr.io/emissary-ingress

    outputs:
      pushed-charts:
        value: ${{ jobs.release.outputs.pushed-charts }}
        description: >-
          TODO
      pushed-images:
        value: ${{ jobs.release.outputs.pushed-images }}
        description: >-
          TODO

permissions:
  contents: read

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    outputs:
      pushed-charts: ${{ steps.push-artifacts.outputs.pushed-charts }}
      pushed-images: ${{ steps.push-artifacts.outputs.pushed-images }}

    steps:
      # 1) pull down image and chart tarballs from actions/upload-artifact@v5
      # 2) unpack and organize tarballs into discrete image / chart bundles
      # 3) push single-arch images to GHCR/DockerHub
      # 4) create and push multi-arch manifest to GHCR/DockerHub
      # 5) push individual chart (ingress & crds) artifacts to GHCR/DockerHub
      # 6) cut an actual GitHub release
      # 7) Party on Wayne
      - name: Checkout
        if: ${{ env.ACT }}
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Install Deps
        if: ${{ env.ACT }}
        uses: ./.github/actions/setup-deps

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker GHCR Auth
        shell: bash
        run: |
          echo ${{ github.token }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin

      - id: download-artifacts
        name: Download CI Artifacts
        uses: actions/download-artifact@v6
        with:
          merge-multiple: true
          path: ${{ github.workspace }}/artifacts

      - id: push-artifacts
        name: Push Release Artifacts
        shell: bash
        continue-on-error: ${{ env.ACT && inputs.debug }}
        env:
          # possible values for `runner.arch`: ["X86", "X64", "ARM", "ARM64"]
          # see https://docs.github.com/en/actions/reference/workflows-and-actions/expressions#example
          # for GitHub's explanation of using conditional logic in expressions
          ARCHES: ${{ (env.ACT == 'true' && (runner.arch == 'X86' && 'AMD64' || runner.arch )) || 'AMD64 ARM64' }}
        run: |
          set -euo pipefail

          trap 'STATUS=${?}; echo >&2 "${0}: Error on line "${LINENO}": ${BASH_COMMAND}"; exit ${STATUS}' ERR

          # NOTE: intended meaning of exit codes match their HTTP status equivilent (e.g., exit code 404 == '(file) not found')

          PUSHED_CHARTS=()
          PUSHED_IMAGES=()
          ARCHES=($(echo ${ARCHES} | tr '[[:upper:]]' '[[:lower:]]'))

          echo -e "pushing images for:\n\tarches: ${ARCHES[@]}\n\tcomponents: ${{ inputs.components }}"

          for COMPONENT in ${{ inputs.components }}; do
              COMPONENT_IMAGES=()

              for ARCH in ${ARCHES[@]}; do
                  IMAGE_PATH="${{ github.workspace }}/artifacts/${COMPONENT}-${ARCH}-image.tar"

                  if [[ ! -f "${IMAGE_PATH}" ]]; then
                      echo "Tarball for ${COMPONENT}/${ARCH} not found at expected path: ${IMAGE_PATH}" 1>&2
                      exit 404  # (file) not found
                  fi

                  LOADED_IMAGE="$(docker load --input "${IMAGE_PATH}" | cut -d' ' -f3)" \
                  || { EXIT_CODE=$?; echo "failed to load image from tarball: ${IMAGE_PATH}" 1>&2; exit ${EXIT_CODE}; }

                  LOADED_TAG="$(echo "${LOADED_IMAGE}" | cut -d':' -f2)"

                  if ! echo "${LOADED_TAG}" | grep -E -- "-${ARCH}$" > /dev/null 2>&1; then
                      LOADED_TAG+="-${ARCH}"
                  fi

                  COMPONENT_ARCH_TAG="${{ inputs.image-registry }}/${COMPONENT}:${LOADED_TAG}"

                  echo "loaded image: ${LOADED_IMAGE}"

                  docker tag "${LOADED_IMAGE}" "${COMPONENT_ARCH_TAG}" \
                  || { EXIT_CODE=$?; echo "failed to tag loaded image: [loaded: ${LOADED_IMAGE}, tag: ${COMPONENT_ARCH_TAG}]" 1>&2; exit ${EXIT_CODE}; }

                  docker push "${COMPONENT_ARCH_TAG}" \
                  || { EXIT_CODE=$?; echo "failed to push tagged component image: ${COMPONENT_ARCH_TAG}" 1>&2; exit ${EXIT_CODE}; }

                  PUSHED_IMAGES+=("${COMPONENT_ARCH_TAG}")
                  COMPONENT_IMAGES+=("--amend" "${COMPONENT_ARCH_TAG}")
              done

              MANIFEST_TAG="$(echo "${COMPONENT_IMAGES[1]}" | sed -E 's#-(arm|amd)64$##Ig')"

              echo "creating multi-arch manifest for: ${MANIFEST_TAG}"

              docker manifest create "${MANIFEST_TAG}" ${COMPONENT_IMAGES[@]} \
              || { EXIT_CODE=$?; echo "failed to create multi-arch manifest: ${MANIFEST_TAG}" 1>&2; exit ${EXIT_CODE}; }

              MANIFEST_SHA="$(docker manifest push "${MANIFEST_TAG}")" \
              || { EXIT_CODE=$?; echo "failed to push multi-arch manifest: ${MANIFEST_TAG}" 1>&2; exit ${EXIT_CODE}; }

              echo "pushed multi-arch manifest: ${MANIFEST_TAG} (digest: ${MANIFEST_SHA})"

              PUSHED_IMAGES+=("${MANIFEST_TAG}")
          done

          echo "pushed-images=${PUSHED_IMAGES[@]}" >> "${GITHUB_OUTPUT}"

          CHART_TARBALLS=($(echo ${{ github.workspace }}/artifacts/emissary-{crds,ingress}-*.tgz))

          if [[ "${#CHART_TARBALLS[@]}" -eq 0 ]]; then
              echo "expected exactly 2 chart tarballs, but found none" 1>&2
              exit 412  # precondition failed
          elif [[ "${#CHART_TARBALLS[@]}" -eq 1 ]]; then
              echo "expected exactly 2 chart tarballs, but only found one: ${CHART_TARBALLS}" 1>&2
              exit 412  # precondition failed
          elif [[ "${#CHART_TARBALLS[@]}" -gt 2 ]]; then
              echo -e \
              "WARNING: expected exactly 2 chart tarballs, but found ${#CHART_TARBALLS[@]}:\n" \
              "$(IFS=$'\n'; echo "${CHART_TARBALLS[*]}" | sed -E 's#^#\t#')"
              echo "WARNING: proceeding with chart pushes, but it'd probably be a " \
              "good idea for an emissary maintainer to double-check the pushed charts"
          fi

          for CHART in ${CHART_TARBALLS[@]}; do
              echo "pushing chart: ${CHART}"

              PUSH_RESULT="$(helm push "${CHART}" oci://${{ inputs.chart-registry }} \
              --username ${{ github.actor }} --password ${{ github.token }} 2>&1)" \
              || { EXIT_CODE=$?; echo "failed to push helm chart tarball: ${CHART}" 1>&2; exit ${EXIT_CODE}; }

              PUSHED_CHART="$(printf '%s\n' "${PUSH_RESULT}" | head -n1 | cut -d' ' -f2)"
              PUSHED_DIGEST="$(printf '%s\n' "${PUSH_RESULT}" | tail -n1 | cut -d' ' -f2)"

              printf 'pushed chart: %s (digest: %s)\n' "${PUSHED_CHART}" "${PUSHED_DIGEST}"

              PUSHED_CHARTS+=("${PUSHED_CHART}")
          done

          echo "pushed-charts=${PUSHED_CHARTS[@]}" >> "${GITHUB_OUTPUT}"

      - id: start-upterm-session
        name: Start upterm session
        shell: bash
        if: ${{ env.ACT == 'true' && (inputs.debug || steps.push-artifacts.outcome == 'failure') }}
        env:
          CONTEXT: |
            {
              "env": ${{ toJSON(env) }},
              "job": ${{ toJSON(job) }},
              "vars": ${{ toJSON(vars) }},
              "needs": ${{ toJSON(needs) }},
              "steps": ${{ toJSON(steps) }},
              "github": ${{ toJSON(github) }},
              "inputs": ${{ toJSON(inputs) }},
              "matrix": ${{ toJSON(matrix) }},
              "runner": ${{ toJSON(runner) }},
              "secrets": ${{ toJSON(secrets) }},
              "strategy": ${{ toJSON(strategy) }}
            }
        run: |
          export CONTEXT="$({ echo '---'; yq -Po yaml --null-input 'env(CONTEXT)'; })"

          expect -c '
          log_user 0
          spawn upterm host --accept -- bash
          expect {
            -re "(yes/no)" { send "yes\r" }
          }
          log_user 1
          interact
          '

          upterm session current

          while pgrep upterm > /dev/null; do
              sleep 5
          done

          if [[ "${{ steps.push-artifacts.outcome == 'failure' }}" == 'true' ]]; then
              exit 500
          fi

#      - id: release-artifacts
#        name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          make_latest: true
#          fail_on_unmatched_files: true
#          tag_name: ${{ inputs.release-tag || github.ref_name }}
#          files: |
#            ${{ github.workspace }}/artifacts/*
#
#      - name: Collect Job Logs
#        uses: ./.github/actions/after-job
#        if: always()
